In [46]:
import numpy as np

def encryption(plain_text):
    ALPHABETS = [chr(i) for i in range(ord('A'), ord('Z')+1)]
    
    key1 = sum(ord(char) for char in plain_text) % 26
    print("Key k1: ",key1)
    
    k2, k3 = 7, 2
    
    P=[(ALPHABETS.index(char)) for char in plain_text]
    
    p1 = [(ALPHABETS.index(char) ^ len(plain_text)) % 26 for char in plain_text]
    

    p2 = [(p_val + key1) % 26 for p_val in p1]
    
    matrix_size = int(np.ceil(len(p2) ** 0.5))
    p3 = np.array(p2 + [0] * (matrix_size ** 2 - len(p2))).reshape(matrix_size, matrix_size)
    p3 = np.rot90(p3, k=-1)                                                                      

    p4 = np.array([((p_val ^ k3) * k2) % 26 for p_val in p3.flatten()])
    
    # Ensure values remain within range 0 to 25
    p4 = p4 % 26
    
    num_zeros = matrix_size ** 2 - len(p4)
    p4_with_zeros = np.append(p4, np.zeros(num_zeros))
    
    # Convert p4_with_zeros to integer dtype
    p4_with_zeros = p4_with_zeros.astype(int)
    print(p4)
    
    subarrays = [p4_with_zeros[i:i+3] for i in range(0, len(p4_with_zeros), 3)]
    for i, subarray in enumerate(subarrays):
        if len(subarray) < 3:
            subarrays[i] = np.append(subarray, [ord(special_char) for special_char in 'AB'])
    
    for i, subarray in enumerate(subarrays):
        subarrays[i][[0, 2]] = subarrays[i][[2, 0]]
    
    merged_array = np.concatenate(subarrays)
    
    merged_array = [(num+k3) % 26 for num in merged_array]
    print(merged_array)
    
    cipher_text = ''.join(ALPHABETS[p_val] for p_val in merged_array)
    
    return cipher_text

plain_text = 'DJSCOE'
cipher_text = encryption(plain_text)
print("Plaintext:", plain_text)
print("Encrypted Data:", cipher_text)

Key k1:  24
[14  0  7 14  2  1 14 14  8]
[9, 2, 16, 3, 4, 16, 10, 16, 16]
Plaintext: DJSCOE
Encrypted Data: JCQDEQKQQ


In [45]:
import numpy as np

def decryption(cipher_text, key1, k2, k3):
    ALPHABETS = [chr(i) for i in range(ord('A'), ord('Z')+1)]
    
    # Convert ciphertext to numbers
    nums = [(ALPHABETS.index(char)) for char in cipher_text]
    print(nums)
    
    # Apply inverse operation of adding k3
    p4 = [(num - k3) % 26 for num in nums]
    print(p4)
    
    # Inverse operation of merging array
    merged_array = np.array([p4[i:i+3] for i in range(0, len(p4), 3)])
    for i in range(len(merged_array)):
        merged_array[i, [0, 2]] = merged_array[i, [2, 0]]
    merged_array = merged_array.flatten()
    
    print(merged_array)
    
    # Inverse operation of applying key1
    p3 = np.array(merged_array).reshape(int(np.sqrt(len(merged_array))), -1)
    p3 = np.rot90(p3)
    
    print(p3)
    
    # Inverse operation of applying k2
    p2 = np.array([((p_val * pow(k2, -1, 26)) ^ k3) % 26 for p_val in p3.flatten()])
    p2 = p2.reshape(int(np.sqrt(len(p2))), -1)
    
    print(p2)
    
    # Inverse operation of applying key1
    p1 = [(p_val - key1) % 26 for p_val in p2.flatten()]
    
    # Inverse operation of applying XOR with length of plaintext
    decrypted_text = ''.join(ALPHABETS[p_val] for p_val in p1)
    
    return decrypted_text

# Example usage
cipher_text = 'LCIQPR'
key1 = 24
k2, k3 = 7, 2
plain_text = decryption(cipher_text, key1, k2, k3)
print("Encrypted Data:", cipher_text)
print("Decrypted Data:", plain_text)


[11, 2, 8, 16, 15, 17]
[9, 0, 6, 14, 13, 15]
[ 6  0  9 15 13 14]
[[ 9 14]
 [ 0 13]
 [ 6 15]]
[[ 3  0  2]
 [11 10 19]]
Encrypted Data: LCIQPR
Decrypted Data: FCENMV
